#!/bin/sh
#
# Generate opsize.h from lib/msgop.tab
#
# This is deliberately generated from C tables, rather than Python's easily
# extractable _numcursori, so as to have a cross check between the languages.
# This may be helpful when msgop.h changes and Python does not follow suit.
#
# TODO: Consider remaking it in Python (for portability)?
#
# From: Rick van Rein <rick@openfortress.nl>


if [ $# -ne 2 ]
then
	echo >&2 "Usage: $0 msgop.tab opsize.h"
	exit 1
fi

msgop_tab="$1"
opsz_h="$2"

(
cat <<EOF
/* FILE GENERATED BY $0 -- DO NOT EDIT */

struct packer_info {
uint16_t numcursori;
};

#define REJECT -1
#define pack(std,str) sizeof (DER_OVLY_##std##_##str) / sizeof (dercursor)

EOF
cat "$msgop_tab" | \
sed -n '/^static const struct packer_info opcode_table \[\] = {$/,/};/p'
) > "$opsz_h"
